version: 2

jobs:
  init-deploy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - checkout
      - run:
          name: Init servers
          command: |
            terraform init
            terraform apply -auto-approve
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: cimg/base:2021.05
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Deploy servers
          command: |
            sudo apt-get update && sudo apt-get install python3.9
            sudo apt-get install python3-pip
            sudo python3 -m pip install pipenv

      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Destroy servers
          command: terraform destroy -auto-approve

workflows:
  version: 2
  deploy_test_destroy:
    jobs:
      - init-deploy
      - deploy:
          requires:
            - init-deploy
      - destroy:
          requires:
            - deploy
