version: 2

jobs:
  init-deploy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light

    steps:
      - checkout

      - run:
          name: Init servers
          command: |
            terraform init
            terraform apply -auto-approve

      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy:
    docker:
      - image: cimg/python:3.9.5

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Deploy servers
          command: |
            pipenv install
            pipenv run install
            pipenv run deploy

      - persist_to_workspace:
          root: .
          paths:
            - .

  test:
    docker:
      - image: cimg/python:3.9.5

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Setup testinfra
          command: |
            python3 -m pip freeze
            python3 -m pip install testinfra[ansible]
            python3 -m pip freeze
            ansible-inventory --graph

      - run:
          name: Testing servers via testinfra
          command: |
            python3 -m pytest -v --ansible-inventory="./inventory/aws_ec2.yml" --hosts=Web --connection=ansible --force-ansible "test-Web-server.py"
            python3 -m pytest -v --ansible-inventory="./inventory/aws_ec2.yml" --hosts=Data --connection=ansible --force-ansible "test-Data-server.py"

      - persist_to_workspace:
          root: .
          paths:
            - .

  destroy:
    docker:
      - image: docker.mirror.hashicorp.services/hashicorp/terraform:light

    steps:
      - attach_workspace:
          at: .

      - run:
          name: Destroy servers
          command: terraform destroy -auto-approve

workflows:
  version: 2
  deploy_test_destroy:
    jobs:
      - init-deploy
      - deploy:
          requires:
            - init-deploy
      - test:
          requires:
            - deploy
      - destroy:
          requires:
            - test
